### ISSUE TITLE
[Med Priority] Navbar selects empty profile pannel

### ISSUE THREAD

**Issue by Cmheidelberg** [CSCI201-FinalProject/OnlineChessGame#7]
If the user is logged in as Guest the navbar will select the empty profile div if the user clicks on a players name from the leaderboards tab
![image](https://user-images.githubusercontent.com/14925268/115972785-4f5f5780-a505-11eb-875e-5ad21f837034.png)

Solution: if user is logged in as guest/not logged in dont highlight the profile div. (or highlight the leaderboards bar instead)

**Comment by sasounkr** [comment]
true

**Comment by jjso-trojan** [comment]
fixed
